# Generated by Django 4.1.5 on 2023-09-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True, auto_now=True)),
                ('roll_no', models.CharField(max_length=10)),
                ('batch', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('trainer', models.CharField(max_length=100)),
                ('total_classes', models.IntegerField(default=0)),
                ('present_classes', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('parent_mobile', models.CharField(max_length=10)),
            ],
        ),
    ]
