# Generated by Django 4.1.5 on 2023-09-09 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appA', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendance',
            new_name='attend',
        ),
    ]
