# Generated by Django 4.1.5 on 2023-09-09 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appA', '0002_rename_attendance_attend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attend',
            name='status',
        ),
    ]
