# Generated by Django 4.1.5 on 2023-09-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appA', '0003_remove_attend_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attend',
            name='name',
            field=models.CharField(default='student', max_length=100),
        ),
    ]
