# Generated by Django 4.1.5 on 2023-09-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appA', '0004_attend_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('trainer', models.CharField(max_length=100)),
                ('total_classes', models.IntegerField(default=0)),
            ],
        ),
    ]
